# Generated by Django 5.1 on 2024-10-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_type', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('earnings', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_working', to='services.servicestype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_working', to='services.servicesworking')),
            ],
        ),
    ]
