# Generated by Django 5.1 on 2024-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestype',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
