# Generated by Django 5.1.2 on 2024-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_servicestype_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesworking",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
