# Generated by Django 5.1 on 2024-08-23 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_first_name_user_full_name_and_more'),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(default='unverified', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_user', to='authentication.user')),
            ],
        ),
    ]
