# Generated by Django 5.1 on 2024-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_leadsusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsusers',
            name='otp_to_verify',
            field=models.CharField(default='0000', max_length=5),
            preserve_default=False,
        ),
    ]
