# Generated by Django 5.1 on 2024-08-23 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_leadsusers_otp_to_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
