# Generated by Django 5.1 on 2024-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_leadsusers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsusers',
            name='compaign_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadsusers',
            name='customer_email',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadsusers',
            name='customer_name',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
