# Generated by Django 5.1 on 2025-01-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_leadsusers_compaign_id_leadsusers_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsusers',
            name='unique_id',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
