# Generated by Django 5.1 on 2025-01-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_leadsusers_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsusers',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
