# Generated by Django 5.1 on 2024-10-07 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageKyc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='kycimage/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='kycimage/')),
                ('status', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kycuser', to='authentication.user')),
            ],
        ),
    ]
