# Generated by Django 5.1 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='upi',
            field=models.CharField(default='N/a', max_length=100),
            preserve_default=False,
        ),
    ]
