# Generated by Django 5.1 on 2025-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawal_upi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='upi',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='ifsc_code',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
