# Generated by Django 5.1 on 2024-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_1', models.ImageField(blank=True, null=True, upload_to='story/')),
                ('story_2', models.ImageField(blank=True, null=True, upload_to='story/')),
                ('story_3', models.ImageField(blank=True, null=True, upload_to='story/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
